name: peroba 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>3.6
  - pandas
  - pip
  - biopython>1.68
  - scikit-bio 
  - scikit-learn 
  - treeswift
  - ete3
  - python-xxhash>2.0.0 # equiv to xxhash 0.8.0
  - mafft>7.467
  - xz
    #- oauth2client
    #- gspread
  - pip:
    - .  # this means run pip on this directory's setup.py 
    - pytools==2020.1
