name: peroba 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mafft
  - raxml-ng
  - parallel
  - iqtree>2
  - python=3.6
  - rapidnj
  - iqtree
  - pandas
  - pip
  - biopython
  - seaborn
  - parasail-python 
  - scikit-bio 
  - scikit-learn 
  - goalign
  - gotree
  - ete3
  - pip:
    - .  # this means run pip on this directory's setup.py 
    - pandas==1.0.1
    - pytools==2020.1
    - pastml
